#!/usr/bin/env python3
"""
One-time importer: converts the CC-BY-licensed Tatoeba sentence pairs
(downloaded from manythings.org/anki, sourced from tatoeba.org) into
content/source/sentences_tatoeba.yaml, in the same shape as the
hand-authored sentences.yaml.

Only real, community-verified translations are used here — nothing is
generated or guessed. Deduplicates against the existing hand-authored
sentences.yaml by normalized English text.
"""
import re
import unicodedata
from pathlib import Path

import yaml

ROOT = Path(__file__).parent.parent.parent
TATOEBA_DIR = ROOT / "build" / "tatoeba"
SOURCE_DIR = ROOT / "content" / "source"


def normalize(text: str) -> str:
    return unicodedata.normalize("NFC", text.strip()).lower()


def parse_tsv(path: Path) -> dict:
    """Returns {normalized_english: (original_english, translation)}."""
    result = {}
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            english, translation = parts[0], parts[1]
            key = normalize(english)
            # Keep first occurrence only (Tatoeba has some near-duplicate sources).
            if key not in result:
                result[key] = (english, translation)
    return result


def classify_level(english: str) -> str:
    word_count = len(english.split())
    if word_count <= 5:
        return "level_1"
    if word_count <= 10:
        return "level_2"
    return "level_3"


CATEGORY_KEYWORDS = {
    "food": ["eat", "food", "rice", "hungry", "drink", "water", "tea", "coffee", "cook"],
    "travel": ["go", "come", "station", "airport", "road", "car", "bus", "train", "walk"],
    "family": ["mother", "father", "brother", "sister", "family", "friend", "child"],
    "time": ["today", "tomorrow", "yesterday", "time", "morning", "night", "hour"],
    "greetings": ["hello", "thank", "sorry", "please", "goodbye", "welcome"],
    "work": ["work", "job", "office", "study", "school", "book", "read", "write"],
}


def classify_category(english: str) -> str:
    lowered = english.lower()
    for category, keywords in CATEGORY_KEYWORDS.items():
        if any(kw in lowered for kw in keywords):
            return category
    return "general"


def main():
    hin_pairs = parse_tsv(TATOEBA_DIR / "hin.txt")
    tam_pairs = parse_tsv(TATOEBA_DIR / "tam.txt")

    existing = yaml.safe_load((SOURCE_DIR / "sentences.yaml").read_text(encoding="utf-8"))
    existing_keys = {normalize(s["english"]) for s in existing.get("sentences", [])}

    all_keys = set(hin_pairs) | set(tam_pairs)
    new_keys = sorted(all_keys - existing_keys)

    entries = []
    for idx, key in enumerate(new_keys):
        hin = hin_pairs.get(key)
        tam = tam_pairs.get(key)
        english = (hin or tam)[0]
        # Skip bare punctuation/interjection-only lines with no letters.
        if not re.search(r"[a-zA-Z]", english):
            continue

        entry = {
            "id": f"tatoeba_{idx}",
            "level": classify_level(english),
            "category": classify_category(english),
            "english": english,
        }
        if tam:
            entry["tamil"] = tam[1]
        if hin:
            entry["hindi"] = hin[1]
        entries.append(entry)

    output = {"sentences": entries}
    out_path = SOURCE_DIR / "sentences_tatoeba.yaml"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "# Sourced from the Tatoeba Project (tatoeba.org) via manythings.org/anki,\n"
            "# licensed CC-BY 2.0 (France). Community-verified translations, not\n"
            "# machine-generated. See content/source/TATOEBA_ATTRIBUTION.md.\n"
            "# Auto-generated by tools/content_compiler/import_tatoeba.py — do not hand-edit.\n\n"
        )
        yaml.dump(output, f, allow_unicode=True, sort_keys=False, width=1000)

    both = sum(1 for k in new_keys if k in hin_pairs and k in tam_pairs)
    only_hin = sum(1 for k in new_keys if k in hin_pairs and k not in tam_pairs)
    only_tam = sum(1 for k in new_keys if k in tam_pairs and k not in hin_pairs)

    print(f"hin.txt pairs: {len(hin_pairs)}")
    print(f"tam.txt pairs: {len(tam_pairs)}")
    print(f"Already in hand-authored sentences.yaml (skipped): {len(all_keys & existing_keys)}")
    print(f"New sentences written: {len(entries)}")
    print(f"  trilingual (en+ta+hi): {both}")
    print(f"  english+hindi only: {only_hin}")
    print(f"  english+tamil only: {only_tam}")
    print(f"-> {out_path}")


if __name__ == "__main__":
    main()
